import { Manrope } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/sidebar";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "Dexter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <main className="flex min-h-screen flex-col items-center justify-between pl-72 p-12 w-full">
          <Sidebar />
          <div className="w-full">{children}</div>
        </main>
      </body>
    </html>
  );
}
